name: 'Terraform'

on:
  workflow_dispatch

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Repo Checkout
      uses: actions/checkout@v2
  
         
    - name: checking the release tag number
      run: |
       echo $GITHUB_REF
