name: 'testing'

on:
  workflow_dispatch

jobs:
  testing:
    name: 'testing'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Repo Checkout
      uses: actions/checkout@v2
  
         
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
     
    - name: build, Tag, push
      run: |
        docker build -t thati/srikanth .
        "docker tag thati/srikanth:latest" "thati/srikanth:${{ github.event.release.tag_name }}"
         docker push thati/srikanth:${{ github.event.release.tag_name }}
