
name: 'testing-sri'

on:
  workflow_dispatch

jobs:
  testing:
    name: 'testing'
    runs-on: github-runner1
    env:
       HOME_PATH: /home/ec2-user/actions-runner/_work/demo/demo/ec2/
       AWS_REGION: us-east-2
    defaults:
      run:
        shell: bash

    steps:
    - name: Repo Checkout
      uses: actions/checkout@v2
      
      
    - name: calling
      run: | 
          chmod 777 shell.sh
          ./shell.sh
          sleep 5
          ls -d */ | tr -d '//' | sed  '/target/d' > $HOME_PATH/repo.txt
